### ISSUE TITLE
Issue with all first nodes

### ISSUE THREAD

**Issue by Simuciokas** [Sashie/skript-yaml#3]
`set {_indexes::*} to skript-yml nodes "" of "config"`
Used to work to get all the first nodes from the file in version 1.0.5. Updated to 1.1.2

Example file
```
version: 1.0
this:
  and:
    value: 1
```
Used to return
`version and this`

Now it returns
`version and this.and.value`
